### ISSUE TITLE
add `update_all_gobin` script

### ISSUE THREAD

**Issue by georgettica** [kortschak/ugbt#2]
as a developer, I don't want to manually `ugbt install` each time there is an update, I want to run a command that will update all of the actions in one sweep.

I am planning on submitting a PR for this. feel free to review

I also want #1 to only install stable versions

**Comment by kortschak** [comment]
The efficiency of version querying is no longer terrible when there are many versions and only update versions are wanted. See 9231b0bd1efa310dc15a19c4502e94997630fd3d.

**Comment by georgettica** [comment]
So it's no longer taxing to use this, and we have a --stable flag.
Not much I can ask for more.

I will anyways post here / create issues if a problem happens from using the script.

**Comment by kortschak** [comment]
Essentially, yes. I'm still leery of adding an all to ugbt itself; kicking off potentially large amounts of network activity without user intervention is not really in the scope of what I was originally intending. This may change.

**Comment by georgettica** [comment]
I can remove the FORCE flag.
This will mean the user will need to add the suffix suggested then pipe it to bash/ copy paste it

**Comment by kortschak** [comment]
7049147d68633907007e526596e56e8248cf6388 adds an update subcommand which means that update all is now essentially just `find $(go env GOBIN) -exec ugbt update '{}' \;`.

**Comment by georgettica** [comment]
changed the script to accomodate for `go env GOBIN` that is empty and to print the binary that is being checked

thanks for the change!
