### ISSUE TITLE
ugbt list --all returns cryptic error

### ISSUE THREAD

**Issue by fgm** [kortschak/ugbt#4]
On most binaries I have tried it, the only result returned by `ugbt list --all <binary>` is this error string:

```ugbt: query proxy: 410 Gone```

The only ones where I don't get this error are open source packages, like https://gitlab.com/fgmarand/gocoverstats, so it might be an issue with private repositories and maybe not taking `$GOPRIVATE` into account.

**Comment by kortschak** [comment]
If you can post the module information printed by running `go version -m /path/to/binary` for one of the failing cases, that would be helpful. `ugbt` doesn't take any notice of $GOPRIVATE. I'm not sure that it makes sense to respect $GOPRIVATE since we only go zero steps into the dependency tree, though maybe it would make the error more informative by bailing early.

**Comment by kortschak** [comment]
Taking a quick look, probably I'm being too harsh in the available versions loop. Please try with the following change.

```diff
index c9d014c..0edd725 100644
--- a/cmd.go
+++ b/cmd.go
@@ -620,7 +620,7 @@ func (t *ugbt) availableVersions(ctx context.Context, mod string) ([]info, error
 
                        i, err := t.info(ctx, url)
                        if err != nil {
-                               return nil, err
+                               continue
                        }
                        versions = append(versions, i)
 
```

**Comment by fgm** [comment]
Thanks for looking into it. I don't think I can give the results of that command, as it provides insights into proprietary code, but in summary:

- path points to a protected repo
- mod is the module at the top of that protected repo
- the first 15 dep lines are public repos
- the next 15 dep lines are private repos
- the remaining 70 dep lines are public repos again

I have of course access to these protected repos.

**Comment by kortschak** [comment]
I think it may be happening because it fails to find the protected repo in the public proxy and because of the line in the diff above that causes a complete failure, when it should just move on to the next proxy. The only relevant line in the module information is the protected repo and its module.

**Comment by fgm** [comment]
It could probably even return a specific access error listing the unavailable lines, indeed.

**Comment by kortschak** [comment]
Please try #5.
