### ISSUE TITLE
some binaries don't have versions to list

### ISSUE THREAD

**Issue by georgettica** [kortschak/ugbt#6]
please see https://github.com/lukehoban/go-outline/issues/10 for the details I found

**Comment by georgettica** [comment]
`goimports`, `go-outline` and others have that issue aswell

**Comment by kortschak** [comment]
This only happens when the currently installed version is at the latest listed version on the proxy. This is how it is working when I try to reproduce this (also shown in the readme for goimports). Unless you can show me details of this failure I believe this is working as intended.
