### ISSUE TITLE
due to go1.18, some binaries are not recompiled with the new version

### ISSUE THREAD

**Issue by georgettica** [kortschak/ugbt#9]
this was found by getting a warning in vscode:
![Screen Shot 2022-04-10 at 13 14 24](https://user-images.githubusercontent.com/11993626/162613478-a07646dc-2b32-4064-9f99-5369b668af28.png)

```
$ go version -m ${GOBIN}/gotests
${GOBIN}/gotests: go1.17.8
	path	github.com/cweill/gotests/gotests
	mod	github.com/cweill/gotests	v1.6.0	h1:KJx+/p4EweijYzqPb4Y/8umDCip1Cv6hEVyOx0mE9W8=
	dep	golang.org/x/tools	v0.0.0-20191109212701-97ad0ed33101	h1:LCmXVkvpQCDj724eX6irUTPCJP5GelFHxqGSWL2D1R0=
$ ugbt list -all gotests
v1.6.0  26 Dec 2020 23:21
v1.5.3   7 Apr 2019 18:20
v1.5.2   8 Nov 2016 17:45
v1.5.1   8 Nov 2016 17:35
v1.5.0   7 Nov 2016 18:16
v1.4.0  19 Jun 2016 04:45
v1.3.0   7 Apr 2016 04:06
$ ugbt update gotests
no new version
```

**Comment by kortschak** [comment]
`ugbt install gotests latest`

`ugbt` doesn't consider Go versions when looking at available updates. That would be a nightmare to maintain and confusing for users.

**Comment by georgettica** [comment]
so I will reinstall these tools again and at least any other user that comes by it will know to do aswell

**Comment by georgettica** [comment]
for the algorithm: the text in the image: 
'Tools (go-outline, gotests, goplay) need recompiling to work with go version go1.18 darwin/amd64'
